// <auto-generated />
using System;
using InventoryPack.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace InventoryPack.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260921220639_AddRequestIdToAsset")]
    partial class AddRequestIdToAsset
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.12");

            modelBuilder.Entity("InventoryPack.Data.Entities.Asset", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("AllocatedAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("CodeGroupId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("PrintedAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("RequestId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CodeGroupId");

                    b.HasIndex("PrintedAt");

                    b.HasIndex("RequestId");

                    b.ToTable("Assets");
                });

            modelBuilder.Entity("InventoryPack.Data.Entities.CodeGroup", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("CodeGroups");
                });

            modelBuilder.Entity("InventoryPack.Data.Entities.LedgerEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Mvo")
                        .HasMaxLength(150)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Quantity")
                        .HasPrecision(18, 4)
                        .HasColumnType("TEXT");

                    b.Property<int>("SourceRowNumber")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SourceTitle")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("TEXT");

                    b.Property<string>("Subaccount")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<string>("Unit")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Mvo", "Subaccount");

                    b.ToTable("LedgerEntries");
                });

            modelBuilder.Entity("InventoryPack.Data.Entities.LedgerEntryCode", b =>
                {
                    b.Property<Guid>("LedgerEntryId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("CodeGroupId")
                        .HasColumnType("TEXT");

                    b.HasKey("LedgerEntryId", "CodeGroupId");

                    b.HasIndex("CodeGroupId");

                    b.ToTable("LedgerEntryCodes");
                });

            modelBuilder.Entity("InventoryPack.Data.Entities.RejectedRow", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Mvo")
                        .HasMaxLength(150)
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("Quantity")
                        .HasPrecision(18, 4)
                        .HasColumnType("TEXT");

                    b.Property<string>("RawText")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<int>("RowNumber")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Subaccount")
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<string>("Unit")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("RowNumber");

                    b.ToTable("RejectedRows");
                });

            modelBuilder.Entity("InventoryPack.Data.Entities.RejectedRowReason", b =>
                {
                    b.Property<Guid>("RejectedRowId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Reason")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("RejectedRowId", "Reason");

                    b.HasIndex("Reason");

                    b.ToTable("RejectedRowReasons");
                });

            modelBuilder.Entity("InventoryPack.Data.Entities.Asset", b =>
                {
                    b.HasOne("InventoryPack.Data.Entities.CodeGroup", "CodeGroup")
                        .WithMany("Assets")
                        .HasForeignKey("CodeGroupId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CodeGroup");
                });

            modelBuilder.Entity("InventoryPack.Data.Entities.LedgerEntryCode", b =>
                {
                    b.HasOne("InventoryPack.Data.Entities.CodeGroup", "CodeGroup")
                        .WithMany("LedgerCodes")
                        .HasForeignKey("CodeGroupId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("InventoryPack.Data.Entities.LedgerEntry", "LedgerEntry")
                        .WithMany("Codes")
                        .HasForeignKey("LedgerEntryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CodeGroup");

                    b.Navigation("LedgerEntry");
                });

            modelBuilder.Entity("InventoryPack.Data.Entities.RejectedRowReason", b =>
                {
                    b.HasOne("InventoryPack.Data.Entities.RejectedRow", "RejectedRow")
                        .WithMany("Reasons")
                        .HasForeignKey("RejectedRowId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("RejectedRow");
                });

            modelBuilder.Entity("InventoryPack.Data.Entities.CodeGroup", b =>
                {
                    b.Navigation("Assets");

                    b.Navigation("LedgerCodes");
                });

            modelBuilder.Entity("InventoryPack.Data.Entities.LedgerEntry", b =>
                {
                    b.Navigation("Codes");
                });

            modelBuilder.Entity("InventoryPack.Data.Entities.RejectedRow", b =>
                {
                    b.Navigation("Reasons");
                });
#pragma warning restore 612, 618
        }
    }
}
