// <auto-generated />
using System;
using InventoryPack.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace InventoryPack.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260914152507_AddQuantityToRejectedRows")]
    partial class AddQuantityToRejectedRows
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.12");

            modelBuilder.Entity("InventoryPack.Data.Entities.Asset", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("InventoryNumber")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("LedgerEntryId")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("PrintedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("UnitIndex")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("InventoryNumber");

                    b.HasIndex("LedgerEntryId");

                    b.HasIndex("PrintedAt");

                    b.HasIndex("InventoryNumber", "UnitIndex")
                        .IsUnique();

                    b.ToTable("Assets");
                });

            modelBuilder.Entity("InventoryPack.Data.Entities.LedgerEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Mvo")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<int>("Quantity")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Subaccount")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Mvo", "Subaccount");

                    b.ToTable("LedgerEntries");
                });

            modelBuilder.Entity("InventoryPack.Data.Entities.RejectedRow", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Mvo")
                        .HasMaxLength(150)
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("Quantity")
                        .HasPrecision(18, 4)
                        .HasColumnType("TEXT");

                    b.Property<string>("RawText")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("TEXT");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<int>("RowNumber")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Subaccount")
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("RowNumber");

                    b.ToTable("RejectedRows");
                });

            modelBuilder.Entity("InventoryPack.Data.Entities.Asset", b =>
                {
                    b.HasOne("InventoryPack.Data.Entities.LedgerEntry", "LedgerEntry")
                        .WithMany("Assets")
                        .HasForeignKey("LedgerEntryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("LedgerEntry");
                });

            modelBuilder.Entity("InventoryPack.Data.Entities.LedgerEntry", b =>
                {
                    b.Navigation("Assets");
                });
#pragma warning restore 612, 618
        }
    }
}
